language: python

sudo: false

python:
    - 2.7
    - 3.5
    - 3.6

install:
   - export PYTHONIOENCODING=UTF8 # just in case
   - pip install pip --upgrade
   - pip install pytest pillow numpy astropy

script:
   - py.test pyavm -p no:warnings
