language: python

sudo: false

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.5
    - 3.6

install:
   - export PYTHONIOENCODING=UTF8 # just in case
   - pip install pytest pillow numpy astropy

script:
   - py.test pyavm
